### ISSUE TITLE
Vylepsit text a obrazek v kapitole Podminky

### ISSUE THREAD

**Issue by pavelsuk** [lutydlitatova/uvod-do-progr-1#2]
Vylepsit text a obrazek na zacatku kapitoly [Podminky](https://kodim.cz/czechitas/uvod-do-progr/prvni-krucky/podminky) tak, aby lekce byla vhodna a prezentovatelna pro vsechny cilove skupiny (zeny/divky/deti).

**Comment by lutydlitatova** [comment]
Viz #3
