### ISSUE TITLE
Zhuštění kapitoly o instalaci Pythonu a editoru (Python a VS Code na jednu stranu)

### ISSUE THREAD

**Issue by ZelenyMartin** [lutydlitatova/uvod-do-progr-1#22]
Tento odkaz [1] je vždy posílán účastnicím před kurzem, proto bych z té kapitoly odstranil povídání o operačním systému a celkově by tam měl být hned návod na instalaci. Povídání bych přesunul do kapitoly Co je to programování [2].

[1] https://kodim.cz/kurzy/uvod-do-progr-1/priprava/jazyky-nastroje
[2] https://kodim.cz/kurzy/uvod-do-progr-1/priprava/programovani/

**Comment by ZelenyMartin** [comment]
CC @pesikj @lutydlitatova

**Comment by pesikj** [comment]
@ZelenyMartin Já na tu kapitolu o programování mám zpracované video, takže na moje kurzy ten odkaz ani nenechávám posílat. Obecně se změnou souhlasím.

**Comment by ZelenyMartin** [comment]
Přemýšlím, že instalace Pythonu a VS Code by měla být společně na jedné stránce (a teprve nepovinné věci na dalších stranách). Bojím se, že by někdo mohl přehlédnout, že potřebuje nainstalovat i VS Code a zbytečně by ho zdržovalo, kdyby zjistil, že nemá vhodný editor.
