### ISSUE TITLE
Ukázka použití funkce input v materiálech

### ISSUE THREAD

**Issue by pesikj** [lutydlitatova/uvod-do-progr-1#24]
Do textu https://kodim.cz/kurzy/uvod-do-progr-1/prvni-krucky/vstup-vystup/prvni-program navrhuji přidat příklad použití funkce `input()` a převedení vstupu na číslo pomocí funkce `int()`. V zadání příkladů to je popsáno, ale nejsem si jist, že to začátečníci bez příkladu použití pochopí.

Dále bych přidal ukázku výstupu s využitím funkce `print()` pro kombinaci řetězce a čísla. Podle mě je nejjednodušší varianta s využitím čárek u funkce `print()`, takže není nutný převod pomocí `str()`. Alternativně je možné využít f-string, ale to je podle mě pro začátečníky v této části kurzu ještě moc složité.

**Comment by ZelenyMartin** [comment]
Urcite souhlasim napsat text o `input()`, `int()` a `str()`. Ja jim to pred cvicenim rikal, ale urcite je lepsi to mit v textu. Taky v kurzu ukazuju, ze `print()` bere vic parametru, takze se hodi to tam mit taky. A souhlasim i s tim f-stringy do UdP1 nedavat.

**Comment by lutydlitatova** [comment]
Souhlas, také to vše říkám a ukazuji, ale v textu to chybí.

f-string asi probírám, teď přesně nevím, ale nevadí mi, když nebude v lekci.
