### ISSUE TITLE
Udělat návod na nefungující python console tab completion ve Windows

### ISSUE THREAD

**Issue by ZelenyMartin** [lutydlitatova/uvod-do-progr-1#25]
Můžete prosím někdo s Windows ověřit řešení v [1], abychom to mohli doplnit do [2]? Díky

[1] https://stackoverflow.com/questions/46944162/python-console-tab-completion-not-working-in-windows
[2] https://kodim.cz/kurzy/uvod-do-progr-1/priprava/jazyky-nastroje

CC @pesikj @lutydlitatova

**Comment by pesikj** [comment]
Možná si to s něčím pletu, ale neměli jsme v plánu psaní do terminálu opustit?

**Comment by ZelenyMartin** [comment]
To je pravda, ale mohlo by to být jako volitelná část pro potřeby DA, kde asi ta python konzole zůstane.

**Comment by ZelenyMartin** [comment]
@pesikj

Má to, prosím tě, být `pip install pyreadline` nebo `pip install pyreadline3`?

Ale je to přeci jen taková okrajová věc. Přemýšlím, jestli je lepší to tam mít nebo spíš ne.

Možná by bylo lepší to dát až do textu do UdP1 [1] a DA kap. _moduly_ [2]

[1] https://kodim.cz/kurzy/uvod-do-progr-1/prvni-krucky/funkce-moduly/moduly
[2] https://kodim.cz/kurzy/python-data/zaklady-programovani/prvni-programy

**Comment by ZelenyMartin** [comment]
Bude realizovano pouze v DA jako issue https://github.com/podlomar/python-data/issues/72
