### ISSUE TITLE
Odsazeni 2 vs 4 mezery

### ISSUE THREAD

**Issue by pixelneo** [lutydlitatova/uvod-do-progr-1#8]
Ahoj, nevim, jestli se to uz nekde neresilo, ale proc se pouzivaji 2 mezery a ne 4 pro odsazovani?

https://peps.python.org/pep-0008/#indentation

**Comment by ZelenyMartin** [comment]
2 mezery jsou tam proto, protože to tak Martin Podloucký napsal a prosazoval konzistenci v kódu s ostatními kurzy HTML/CSS/JavaScript. Teď už se ale vzdal rozhodování nad obsahem Python kurzů, takže to s Lídou a Jirkou změníme na 4 mezery.
